module.exports = {
  OrderPage: {
    orders_subtab: '#subtab-AdminParentOrders',
    form: '#form-order',
    view_order_button: '//*[@id="form-order"]//tr[%NUMBER]//div[contains(@class,"pull-right")]//a',
    order_state_select: '//*[@id="id_order_state"]',
    update_status_button: '//*[@id="status"]/form//button[@name="submitState"]',
    order_quantity: '//*[@id="orderProducts"]//span[contains(@class,"quantity_show")]',
    available_quantity: '//*[@id="orderProducts"]//td[contains(@class,"product_stock")]',
    order_status: '//*[@id="status"]//table[contains(@class,"history-status")]//tr[1]/td[2]',
    shipping_cost: '//*[@id="shipping_table"]//tr[1]//td[5]/span',
    message_order: '//*[@id="content"]//div[@class="message-body"]//p[@class="message-item-text"]',
    product_Url: '//*[@id="orderProducts"]//tr[1]/td[2]/a',
    edit_product_button: '//*[@id="orderProducts"]//button[contains(@class,"edit_product_change_link")]',
    product_basic_price: '//*[@id="orderProducts"]//tr[1]//input[contains(@class,"edit_product_price_tax_incl")]',
    customer_name: '//*[@id="content"]//div[@class="message-body"]//h4[@class="message-item-heading"]',
    order_submenu: '//*[@id="subtab-AdminOrders"]/a',
    document_submenu: '//*[@id="tabOrder"]//a[@href="#documents"]',
    download_invoice_button: '(//*[@id="documents_table"]//a[contains(@href, "generateInvoicePDF")])[1]',
    download_delivery_button: '//*[@id="documents_table"]//tr[3]/td[3]/a',
    product_name: '//*[@id="orderProducts"]//tr[1]//span[@class="productName"]',
    total_price: '//*[@id="total_products"]/td[contains(@class,"amount")]',
    shipping_method: '//*[@id="shipping_table"]//tr/td[3]',
    search_by_reference_input: '//*[@id="form-order"]//table[contains(@class,"order")]//input[@name="orderFilter_reference"]',
    search_order_button: '//*[@id="submitFilterButtonorder"]',
    first_order: '//*[@id="form-order"]//table//tbody//tr[1]//a',
    transform_guest_customer_button: '//*[@id="content"]//input[@name="submitGuestToCustomer"]',
    payment_amount: '//*[@id="formAddPayment"]//tbody/tr[1]/td[4]',
    outside: '(//*[@id="content"]//div/span[@class="value"])[1]',
    product_base_price: '//*[@id="orderProducts"]//tr[1]/td[3]/span',
    total_product_TTC: '//*[@id="orderProducts"]//tr[1]/td[@class="total_product"]',
    voucher_name: '//*[@id="start_products"]//div[contains(@class,"panel-vouchers")]//tbody//tr[1]',
    voucher_value: '//*[@id="start_products"]//div[contains(@class,"panel-vouchers")]//tbody//tr[1]/td[2]',
    total_discount: '//*[@id="total_discounts"]/td[2]',
    total_shipping_price: '//*[@id="total_shipping"]/td[2]',
    total_cart: '//*[@id="total_order"]/td[2]/strong',
    product_information_page: '//*[@id="orderProducts"]//span[contains(text(), "%NAME")]',
    customer_informations_link: '//*[@id="content"]//span[@class="badge"]/a',
    customer_email: '//*[@id="content"]//dd/a',
    account_registered: '//*[@id="content"]//dd[@class="text-muted"]',
    valid_orders_placed: '//*[@id="content"]//dl[@class="well list-detail"]//span[@class="badge"]',
    total_spent_since_registration: '//*[@id="content"]//dl[@class="well list-detail"]//span[contains(@class,"badge-success")]',
    shipping_address: '//*[@id="addressShipping"]//div[@class="col-sm-6"]',
    invoice_address: '//*[@id="addressInvoice"]//div[@class="col-sm-6"]',
    invoice_address_button: '//*[@id="tabAddresses"]//a[@href="#addressInvoice"]',
    shipping_informations: '//*[@id="shipping_table"]//td[%NUMBER]',
    payment_informations: '//*[@id="formAddPayment"]//tr[1]/td[%NUMBER]',
    order_reference: '(//*[@id="content"]//div[@class="panel-heading"]//span[1])[1]'
  },
  CreateOrder: {
    new_order_button: '//*[@id="page-header-desc-order-new_order"]',
    customer_search_input: '//*[@id="customer"]',
    choose_customer_button: '//*[@id="customers"]/div[1]/div/div[2]/button',
    details_customer_button: '//*[@id="customers"]//a',
    social_title_details: '(//*[@id="container-customer"]//p)[1]',
    last_visit_details: '(//*[@id="container-customer"]//p)[4]',
    orders_button: '//*[@id="old_carts_orders_navtab"]//a[@href="#lastOrders"]',
    carts_button: '//*[@id="old_carts_orders_navtab"]//a[@href="#nonOrderedCarts"]',
    product_search_input: '//*[@id="product"]',
    quantity_cart_input: '//*[@id="qty"]',
    quantity_product_input: '//*[@id="customer_cart"]//input[@class="cart_quantity"]',
    add_to_cart_button: '//*[@id="submitAddProduct"]',
    order_message_textarea: '//*[@id="order_message"]',
    delivery_option: '//*[@id="delivery_option"]',
    payment: '//*[@id="payment_module_name"]',
    total_shipping: '//*[@id="total_shipping"]',
    create_order_button: '//*[@id="summary_part"]//button[@name="submitAddOrder"]',
    product_combination: '//*[@class="id_product_attribute"]',
    basic_price_value: '//*[@id="customer_cart"]//tr[1]//input[@class="product_unit_price"]',
    product_select: '//*[@id="id_product"]',
    combination_select: '//*[@class="id_product_attribute" and not(contains(@style, "none"))]',
    new_customer_button: '//*[contains(@id,"search-customer")]//a[contains(@class,"btn-default")]',
    orders_table: 'lastOrders',
    search_button: '//*[@id="products_part"]//span[@class="input-group-addon"]',
    delete_product_button: '//*[@id="customer_cart"]//a[contains(@class,"delete_product")]',
    increase_quantity_button: '//*[@id="customer_cart"]//a[contains(@class,"increaseqty_product")]',
    decrease_quantity_button: '//*[@id="customer_cart"]//a[contains(@class,"decreaseqty_product")]',
    total_price: '//*[@id="customer_cart"]//td[6]',
    currency_select: '//*[@id="id_currency"]',
    language_select: '//*[@id="id_lang"]',
    add_new_voucher_button: '//*[@id="vouchers_part"]//a[contains(@class,"btn-default")]',
    delete_voucher_button: '//*[@id="voucher_list"]//a[contains(@class,"delete_discount")]',
    voucher_input: '//*[@id="voucher"]',
    product_name: '//*[@id="customer_cart"]//td[2]',
    search_voucher_option: '//li[contains(text(),"%T")]',
    voucher_value: '//*[@id="voucher_list"]//td[3]',
    edit_delivery_address_button: '//*[@id="edit_delivery_address"]',
    check_delivered_address: '//*[@id="address_delivery_detail"]',
    check_invoice_address: '//*[@id="address_invoice_detail"]',
    delivery_address_select: '//*[@id="id_address_delivery"]',
    invoice_address_select: '//*[@id="id_address_invoice"]',
    add_new_address_button: '//*[@id="new_address"]',
    shipping_price_tax_incl: '//*[@id="shipping_price"]/b',
    shipping_price_tax_excl: '//*[@id="total_shipping"]',
    enable_free_shipping: '//*[@id="carrier_form"]//span/label[@for="free_shipping"]',
    disable_free_shipping: '//*[@id="carrier_form"]//span/label[@for="free_shipping_off"]',
    total_cart_TTC: '//*[@id="total_with_taxes"]',
    total_cart_HT: '//*[@id="total_without_taxes"]',
    product_price_cart: '//*[@id="customer_cart"]//tr/td[6]',
    total_taxes: '//*[@id="total_taxes"]',
    total_voucher_HT: '//*[@id="total_vouchers"]',
    total_product_HT: '//*[@id="total_products"]',
    shipping_name: '//*[@id="delivery_option"]/option[%NUMBER]',
    payment_method: '//*[@id="payment_module_name"]/option[@value="VALUE"]',
    customer_email: '(//*[@id="content"]//div[@class="panel"]/a)[1]',
    close_frame: '//a[@title="Close"]',
    carts_buttons: '//*[@id="nonOrderedCarts"]//tr[1]/td[4]/a[%NUMBER]',
    orders_buttons: '//*[@id="lastOrders"]//tr[1]/td[7]/a[%NUMBER]'
  },
  CustomerInformations: {
    registration_date: '(//*[@id="container-customer"]//p[contains(@class,"static")])[3]',
    valid_orders: '(//*[@id="container-customer"]//div[@class="panel"]//span[contains(@class,"label-success")])[1]',
    customer_email: '(//*[@id="container-customer"]//div[@class="panel-heading"]/a)[1]',
    orders_total_amount: '(//*[@id="container-customer"]//div[@class="col-lg-6"])[2]'
  },
  OrderDetailsPage: {
    order_reference: '(//*[@id="content"]/div[3]//span[1])[5]'
  }
};

