module.exports = {
  accountPage: {
    create_button: '[data-link-action="display-register-form"]',
    firstname_input: '//*[@id="customer-form"]//input[@name="firstname"]',
    lastname_input: '//*[@id="customer-form"]//input[@name="lastname"]',
    email_input: '//*[@id="customer-form"]//input[@name="email"]',
    password_input: '//*[@id="customer-form"]//input[@name="password"]',
    customer_form_continue_button: '//*[@id="customer-form"]//button[@name="continue"]',
    save_account_button: '[data-link-action="save-customer"]',
    checkout_step: '//*[@id="checkout-personal-information-step"]/h1',
    checkout_addresses_step: '//*[@id="checkout-addresses-step"]',
    radio_button_gender: '(//*[@id="customer-form"]//input[contains(@name,"id_gender")])[2]',
    account_link: '//*[@id="_desktop_user_info"]//a[@class="account"]',
    add_first_address: '#address-link',
    adr_first_name: '//*[@id="delivery-address"]//input[@name="firstname"]',
    adr_last_name: '//*[@id="delivery-address"]//input[@name="lastname"]',
    adr_address: '//*[@id="content"]//input[@name="address1"]',
    adr_postcode: '//*[@id="content"]//input[@name="postcode"]',
    checkout_personal_information_step: '//*[@id="checkout-personal-information-step"]',
    adr_city: '//*[@id="content"]//input[@name="city"]',
    adr_save: '//*[@id="content"]//footer/button',
    success_alert: '[data-alert="success"]',
    adr_update: '[data-link-action="edit-address"]',
    delivery_addresses: '//*[@id="delivery-addresses"]',
    delivery_address_continue: '//*[@id="delivery-address"]//button[@name="confirm-addresses"]',
    invoice_address_continue: '//*[@id="invoice-address"]//button[@name="confirm-addresses"]',
    confirm_delivery_option: '//*[@id="js-delivery"]/button',
    first_address: '//*[@id="id-address-delivery-address-1"]',
    confirm_address_button: '//*[@id="checkout-addresses-step"]//button[@name="confirm-addresses"]',
    different_address: '//*[@id="checkout-addresses-step"]//a[contains(@data-link-action,"invoice")]',
    invoice_address_form: '//*[@id="invoice-address"]',
    delivery_form: '//*[@id="checkout-delivery-step"]',
    delivery_option_list: '//*[@id="checkout-delivery-step"]//div[@class="delivery-options-list"]',
    summary_cart: '//*[@id="js-delivery"]//label[@for="input_gift"]',
    delivery_option: '//*[@id="delivery_option_%NUMBER"]',
    delivery_step: '//*[@id="checkout-delivery-step"]',
    conditons_form: '//*[@id="conditions-to-approve"]',
    payment_confirmation_button: '//*[@id="payment-confirmation"]//button',
    terms_and_conditions: '//*[@id="conditions_to_approve[terms-and-conditions]"]',
    payment_option: '//*[@id="payment-option-%NUMBER"]',
    order_confirmation: '//*[@id="order-confirmation"]',
    //------------------ connect with existing account from checkout ---------------//
    sign_tab: '//*[@id="checkout-personal-information-step"]//a[contains(text(), "Sign in")]',
    signin_email_input: '//*[@id="login-form"]//input[@name="email"]',
    signin_password_input: '//*[@id="login-form"]//input[@name="password"]',
    continue_button: '//*[@id="login-form"]//button[contains(@class, "continue")]',
    //---------------------- create account from checkout -------------------------//
    new_customer_btn: '[data-link-action="register-new-customer"]',
    new_address_btn: '[name="confirm-addresses"]',
    new_email_input: '//*[@id="customer-form"]//input[@name="email"]',
    new_password_input: '//*[@id="customer-form"]//input[@name="password"]',
    shipping_continue_btn: '//*[@id="js-delivery"]/button[@name="confirmDeliveryOption"]',
    pay_by_check: '//*[@id="payment-option-1"]',
    terms_of_service: '//*[@id="conditions_to_approve[terms-and-conditions]"]',
    customer_form: '//*[@id="customer-form"]',
    order_button: '//*[@id="payment-confirmation"]//button',
    confirmed_order_message: '//*[@id="content-hook_order_confirmation"]//h3[contains(@class, "card-title")]',
    email_sent_message: '//*[@id="content-hook_order_confirmation"]//p',
    notification_save_adr: '//*[@id="notifications"]//li',
    add_new_address: '//*[@id="checkout-addresses-step"]//p[@class="add-address"]/a'
  }
};
