module.exports = {
  CarrierSubMenu: {
    submenu: '//*[@id="subtab-AdminCarriers"]/a',
    new_carrier_button: '//*[@id="page-header-desc-carrier-new_carrier"]/i',
    name_input: '//*[@id="name"]',
    transit_time: '//*[@id="delay_1"]',
    speed_grade: '//*[@id="grade"]',
    logo: '//*[@id="carrier_logo_input"]',
    tracking_url: '//*[@id="url"]',
    next_button: '//*[@id="carrier_wizard"]//a[@class="buttonNext btn btn-default"]',
    shipping_handling: '//*[@id="fieldset_form_1"]//label[@for="shipping_handling_on"]',
    billing_price: '//*[@id="billing_price"]',
    billing_weight: '//*[@id="billing_weight"]',
    range: '//*[@id="zones_table"]/tbody/tr[%id]/td[3]/div/input',
    all_zone: '//*[@id="zones_table"]/tbody/tr[@class="fees_all"]/td/input',
    max_width: '//*[@id="max_width"]',
    max_hieght: '//*[@id="max_height"]',
    max_depth: '//*[@id="max_depth"]',
    max_weight: '//*[@id="max_weight"]',
    finish_button: '//*[@id="carrier_wizard"]//a[@class="buttonFinish btn btn-success"]',
    steps: '//*[@id="carrier_wizard"]/ul/li[%id]/a',
    search_input: '//*[@id="table-carrier"]//input[@name="carrierFilter_name"]',
    search_button: '//*[@id="submitFilterButtoncarrier"]',
    update_button: '//*[@id="table-carrier"]//a[@class="edit btn btn-default"]',
    green_validation: '//*[@id="content"]/div[@class="bootstrap"]/div[@class="alert alert-success"]',
    icon: '//*[@id="table-carrier"]/tbody//i[@class="icon-caret-down"]',
    delete_button: '//*[@id="table-carrier"]//a[@class="delete"]',
    reset_button:'//*[@id="table-carrier"]/thead//button[@name="submitResetcarrier"]'
  }
}; 